### ISSUE TITLE
RSA Key Support

### ISSUE THREAD

**Issue by citizentim** [TeslaGov/ngx-http-auth-jwt-module#27]
Am I correct in stating that this module currently supports only symmetric keys, but not asymmetric RSA private key-signed tokens?  If so, I would like to make a feature request to support tokens signed by RSA keys.  

I'm specifically looking for RS256.

Thank you!

**Comment by fitzyjoe** [comment]
Yes, this currently only supports symmetric keys.  libjwt, the C library I'm using under the covers supports asymmetric keys so it would be possible to enhance this module and continue to use libjwt.  I don't have a business need at the moment for this, but I would welcome a pull request.

**Comment by citizentim** [comment]
Hey Fitzyjoe, I totally understand about not having a business need.  I've just sent a pull request with the RSA validation functionality.

**Comment by citizentim** [comment]
Closing as PR has been merged. Thanks, @fitzyjoe!

**Comment by kevinmichaelchen** [comment]
For posterity: see #31
