### ISSUE TITLE
libjwt 1.9.0?

### ISSUE THREAD

**Issue by KensingtonTech** [TeslaGov/ngx-http-auth-jwt-module#38]
I've noticed that the Dockerfile uses libjwt 1.8.0, so I've taken that to mean that that's what's officially supported.  Would any work be needed to support 1.9.0?

I asked because I've undertaken the work to implement this in MacPorts (still waiting on PR https://github.com/macports/macports-ports/pull/1925 to be merged) but this also meant adding libjwt to MacPorts (https://github.com/macports/macports-ports/pull/1924).  Because of the whole version 1.8.0 thing, that's what I implemented in MacPorts, but their team is pressing me to implement the latest.  And because MacPorts doesn't implement versioned dependencies, I'm resisting until this project blesses libjwt 1.9.0.

Cheers, gents.

**Comment by fitzyjoe** [comment]
I bumped libjwt from 1.8.0 to 1.9.0 and the tests pass.  Thanks for your work on MacPorts.  I can see a rpm build for this at some point in the future.
