### ISSUE TITLE
Remove X- header prefix

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/ngx-http-auth-jwt-module#45]
> Custom proprietary headers can be added using the 'X-' prefix, but this convention was deprecated in June 2012, because of the inconveniences it caused when non-standard fields became standard in [RFC-6648](https://tools.ietf.org/html/rfc6648)

## Proposal
Add `auth_jwt_header_prefix` to allow users to specify custom header prefix.

e.g., 
```
auth_jwt_header_prefix "clarakm"
```

Then `x-email` and `x-userid` would be renamed to `clarakm-email` and `clarakm-userid`.

**Comment by fitzyjoe** [comment]
Please don’t change!

**Comment by kevinmichaelchen** [comment]
I won't change any code. Is it a valid issue?

**Comment by kevinmichaelchen** [comment]
This is too difficult of a task. It's not as simple as changing two strings. Closing.
