### ISSUE TITLE
Best practice to validate multiple JWT

### ISSUE THREAD

**Issue by vlauciani** [TeslaGov/ngx-http-auth-jwt-module#47]
Hi 

What is the best practice to validate multiple JWT?

I've a lot of users and each user have a personal JWT; each user can access to one o more 'location'/'route'.
Should I create, for example, a `test-jwt-nginx.conf` for each user?

Thank you,
Valentino

**Comment by fitzyjoe** [comment]
I'm not completely understanding your question.  Are the JWTs all signed with the same key/secret or different ones?  This module supports multiple different keys for different locations, but not multiple keys for the same location.  Of course there are infinite JWTs that this module supports for the same key.  I know this is an old comment but if you care to elaborate I'm interested.

**Comment by JoshMcCullough** [comment]
Closing this since there was no response. Feel free to reopen if needed, @vlauciani.
