### ISSUE TITLE
Test token not a valid JWT token

### ISSUE THREAD

**Issue by katsar0v** [TeslaGov/ngx-http-auth-jwt-module#49]
![image](https://user-images.githubusercontent.com/7236157/50700983-6637c280-104c-11e9-9b14-8b5e38b6e542.png)
Here you can see, I used the secret and the token from test.sh.. it is just not valid, even if the key base64 encoded.

**Comment by frank1649** [comment]
Hi, is there a follow up on this? I Have the same question.
The authentication will not pass when I use my own token and secret, which are valid on the JWT debugger.

**Comment by frank1649** [comment]
Found the answer here: https://github.com/benmcollins/libjwt/issues/79
