### ISSUE TITLE
Leveraging JWT Claims for Logging purpose

### ISSUE THREAD

**Issue by Nitroboy** [TeslaGov/ngx-http-auth-jwt-module#52]
Hi,

This may be a newbie question but does this module support JWT Claim retrieval from incoming request header as mentionned here ? :  [https://www.nginx.com/blog/authenticating-api-clients-jwt-nginx-plus/#auth_jwt](url)
You can see on the link above that some variables (such as $jwt_header_xxxx and $jwt_claim_xxxx) representing JWT header and payload fields are available and can be sent to the forwarded API server for request processing per user.
The readme doesn't mention such variables.
More generally, does this module offer the same functionalities as the one coming natively with NGINX Plus which is called "ngx_http_auth_jwt_module".

Thanks in advance for your help

**Comment by fitzyjoe** [comment]
@Nitroboy This module does not support the variables you mention above.  This module is not the same or compatible with the native NGINX Plus module.  This module was written from scratch.  Thanks for your interest and sorry I took so long to respond.  I did not have a need to do anything with this project for a couple of years, but I'm about to update it.
