### ISSUE TITLE
Just wanted to say "Thank you"

### ISSUE THREAD

**Issue by venomone** [TeslaGov/ngx-http-auth-jwt-module#67]
@fitzyjoe @max-lt @KensingtonTech @kevinmichaelchen @penumbra23 
I just wanted to say thank you for your nice work onto this nginx module, we're using it with great success.
It really solves a lot of issues for us. I basically didn't saw many posts like this one here on GitHub, so I wanted to start
as a good example. So again, thank you guys very much for your great work :D 

Thumbs up : +1:

**Comment by JoshMcCullough** [comment]
Glad you found it useful! Thanks for the note.
