### ISSUE TITLE
Compatibility with nginx 1.23.0+

### ISSUE THREAD

**Issue by fgnix** [TeslaGov/ngx-http-auth-jwt-module#82]
From version 1.23.0 Nginx changed internal API: header lines are represented as linked lists.

r->headers_in.cookies has been renamed to r->headers_in.cookie

As described in this commit:
https://github.com/nginx/nginx/commit/3aef1d693f3cc431563a7e6a6aba6a34e5290f03

**Comment by tomer-cyera** [comment]
+1

**Comment by Schamschula** [comment]
Disabling jwt variant for nginx 1.24.0 under MacPorts. I had previously removed the module for nginx-devel (1.23.x).

**Comment by JoshMcCullough** [comment]
Sorry for the late response. We'll add a compile-time flag to handle this.
