### ISSUE TITLE
1.24 module doesn't 'seem' to be compiled against nginx 1.24.0

### ISSUE THREAD

**Issue by matt-mercer** [TeslaGov/ngx-http-auth-jwt-module#96]
Hi ..

I downloaded the prebuilt:
https://github.com/TeslaGov/ngx-http-auth-jwt-module/releases/download/2.0.1/ngx_http_auth_jwt_module_2.0.1_nginx_1.24.0.tgz

and tried to use this with nginx 1.24
from https://nginx.org/packages/debian/pool/nginx/n/nginx/nginx_1.24.0-1~bullseye_amd64.deb

when trying to load the module .. I get:

nginx: [emerg] module "/etc/nginx/modules/ngx_http_auth_jwt_module.so" version 1022001 instead of 1024000 in /etc/nginx/nginx.conf:5

![image](https://user-images.githubusercontent.com/449892/236167902-64f0d358-1c5a-41a7-bdbd-0e210b6b6d97.png)

**Comment by matt-mercer** [comment]
ok .. confirmed .. the 1.24 module is accepted with nginx 1.22.1

![image](https://user-images.githubusercontent.com/449892/236169903-0d09bf0c-a88c-454a-ae91-dba0a077a8ef.png)

**Comment by JoshMcCullough** [comment]
Fixed the `make_release` script to properly set the `NGINX_VERSION`. New binaries have been uploaded to [the release](https://github.com/TeslaGov/ngx-http-auth-jwt-module/releases/tag/2.0.1).

Thanks for letting us know!
